{
  "checkpoints": [
    "{\n  \"trainable_name\": \"PPO\",\n  \"trial_id\": \"a8e69_00000\",\n  \"config\": {\n    \"env\": \"TradingEnv\",\n    \"model\": {\n      \"fcnet_hiddens\": [\n        256,\n        256\n      ],\n      \"fcnet_activation\": \"relu\",\n      \"use_lstm\": true,\n      \"max_seq_len\": 60,\n      \"lstm_cell_size\": 256,\n      \"lstm_use_prev_action\": true,\n      \"lstm_use_prev_reward\": true\n    },\n    \"env_config\": {\n      \"window_size\": 25\n    },\n    \"log_level\": \"DEBUG\",\n    \"framework\": \"torch\",\n    \"ignore_worker_failures\": true,\n    \"num_workers\": 1,\n    \"num_gpus\": 0,\n    \"clip_rewards\": true,\n    \"lr\": 8e-06,\n    \"gamma\": 0,\n    \"observation_filter\": \"MeanStdFilter\",\n    \"lambda\": 0.72,\n    \"vf_loss_coeff\": 0.5,\n    \"entropy_coeff\": 0.01,\n    \"eager_tracing\": true\n  },\n  \"local_dir\": \"/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO\",\n  \"evaluated_params\": {},\n  \"experiment_tag\": \"0\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"resources\": {\n    \"cpu\": 1,\n    \"gpu\": 0,\n    \"memory\": 0,\n    \"object_store_memory\": 0,\n    \"extra_cpu\": 1,\n    \"extra_gpu\": 0,\n    \"extra_memory\": 0,\n    \"extra_object_store_memory\": 0,\n    \"custom_resources\": {},\n    \"extra_custom_resources\": {}\n  },\n  \"stopping_criterion\": {\n    \"episode_reward_mean\": 45\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"last_result\": {},\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1612805138.080008,\n  \"logdir\": \"/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO/PPO_TradingEnv_a8e69_00000_0_2021-02-09_01-25-38\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO/PPO_TradingEnv_a8e69_00000_0_2021-02-09_01-25-38/error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/tune/trial_runner.py\\\", line 519, in _process_trial\\n    result = self.trial_executor.fetch_result(trial)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py\\\", line 497, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/worker.py\\\", line 1379, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(RuntimeError): \\u001b[36mray::PPO.train()\\u001b[39m (pid=2658303, ip=192.168.88.226)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/tune/trainable.py\\\", line 183, in train\\n    result = self.step()\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/agents/trainer_template.py\\\", line 147, in step\\n    res = next(self.train_exec_impl)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 756, in __next__\\n    return next(self.built_iterator)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 843, in apply_filter\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 843, in apply_filter\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  [Previous line repeated 1 more time]\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 876, in apply_flatten\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 828, in add_wait_hooks\\n    item = next(it)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  [Previous line repeated 1 more time]\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 471, in base_iterator\\n    yield ray.get(futures, timeout=timeout)\\nray.exceptions.RayTaskError(AttributeError): \\u001b[36mray::RolloutWorker.par_iter_next()\\u001b[39m (pid=2658296, ip=192.168.88.226)\\n  File \\\"python/ray/_raylet.pyx\\\", line 463, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 415, in ray._raylet.execute_task.function_executor\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/util/iter.py\\\", line 1152, in par_iter_next\\n    return next(self.local_it)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\\\", line 323, in gen_rollouts\\n    yield self.sample()\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/evaluation/rollout_worker.py\\\", line 638, in sample\\n    batches = [self.input_reader.next()]\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\\\", line 94, in next\\n    batches = [self.get_data()]\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\\\", line 211, in get_data\\n    item = next(self.rollout_provider)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/evaluation/sampler.py\\\", line 651, in _env_runner\\n    base_env.send_actions(actions_to_send)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/env/base_env.py\\\", line 346, in send_actions\\n    self.vector_env.vector_step(action_vector)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/env/vector_env.py\\\", line 143, in vector_step\\n    obs, r, done, info = self.envs[i].step(actions[i])\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/tensortrade/env/generic/environment.py\\\", line 121, in step\\n    self.action_scheme.perform(self, action)\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/tensortrade/env/default/actions.py\\\", line 90, in perform\\n    orders = self.get_orders(action, self.portfolio)\\n  File \\\"main_simple.py\\\", line 70, in get_orders\\n    listener.on_action(action)\\nAttributeError: 'SimpleProfit' object has no attribute 'on_action'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\n\\u001b[36mray::PPO.train()\\u001b[39m (pid=2658303, ip=192.168.88.226)\\n  File \\\"python/ray/_raylet.pyx\\\", line 456, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 459, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 463, in ray._raylet.execute_task\\n  File \\\"python/ray/_raylet.pyx\\\", line 415, in ray._raylet.execute_task.function_executor\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\\\", line 499, in train\\n    self._try_recover()\\n  File \\\"/home/davidfan/miniconda3/envs/RL/lib/python3.8/site-packages/ray/rllib/agents/trainer.py\\\", line 1117, in _try_recover\\n    raise RuntimeError(\\nRuntimeError: Not enough healthy workers remain to continue.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"checkpoint_freq\": 0,\n  \"checkpoint_at_end\": true,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059566010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d9475628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9475628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f9475622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_nonjson_fields\": [\n    \"results\",\n    \"best_result\",\n    \"param_config\",\n    \"extra_arg\"\n  ],\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_metric": null,
    "_total_time": 0,
    "_iteration": 2,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1612805138.035097,
    "_last_checkpoint_time": 1612805143.2845833,
    "_checkpoint_period": 10,
    "_session_str": "2021-02-09_01-25-38",
    "checkpoint_file": "/home/davidfan/VLL/FX/tensortrade/2_PPO-lstm-BTCUSD/results_PPO/PPO/experiment_state-2021-02-09_01-25-38.json",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1612805138.035097,
    "timestamp": 1612805143.2845833
  }
}